export default [
  {
    "id": "9c1e4a28-454b-4058-8e04-a0daaa7fd729",
    "avatar_url" : 'http://lorempixel.com/640/480/people/',
    "employee_id": "",
    "first_name": "Emp_01",
    "last_name": "User",
    "nickname": null,
    "email": "emergency_01@csvnew.com",
    "date_of_birth": "1975-08-20",
    "home_phone": null,
    "cell_phone": "123-321-1234",
    "social_security_number": "XXX-XX-7892",
    "gender": "Male",
    "marital_status": "Married",
    "employment_status": "Active",
    "employment_type": "Full-time",
    "job_category": "Management",
    "title": null,
    "role": "company_admin",
    "department": "Sales",
    "manager": {
      "id": null,
      "first_name": null,
      "last_name": null,
      "email": null
    },
    "location": "Omaha",
    "address1": "17305 Davenport St",
    "address2": null,
    "city": "Omaha",
    "state": "",
    "zip_code": "68118",
    "country": "US",
    "hire_date": "1981-01-01",
    "termination_date": null,
    "rehire_date": null,
    "created_at": "2017-07-25T13:10:45.013-07:00",
    "updated_at": "2017-08-17T15:15:12.564-07:00",
    "custom_fields": [
      {
        "id": 1,
        "field_name": "Custom1",
        "field_type": "Select",
        "field_value": "a,b,c,d",
        "field_destination": "employment_compensation",
        "field_display_name": "",
        "user_imports_display": "Custom1 (1. custom employment select field)"
      },
      {
        "id": 2,
        "field_name": "Custom4",
        "field_type": "Float",
        "field_value": "108.00",
        "field_destination": "employment_compensation",
        "field_display_name": null,
        "user_imports_display": "Custom4 (2. custom employment float field)"
      },
      {
        "id": 3,
        "field_name": "Custom6",
        "field_type": "Multivalue",
        "field_value": "ABC,DEF,EFG",
        "field_destination": "employment_compensation",
        "field_display_name": "cust32dsd",
        "user_imports_display": "Custom6 (3. custom employment multivalue field)"
      },
      {
        "id": 4,
        "field_name": "Custom2",
        "field_type": "Boolean",
        "field_value": "false",
        "field_destination": "personal_information",
        "field_display_name": null,
        "user_imports_display": "Custom2 (4. custom personal boolean field)"
      },
      {
        "id": 5,
        "field_name": "Custom3",
        "field_type": "Date",
        "field_value": "01/01/2016",
        "field_destination": "personal_information",
        "field_display_name": null,
        "user_imports_display": "Custom3 (5. custom personal date field)"
      },
      {
        "id": 6,
        "field_name": "Custom5",
        "field_type": "Integer",
        "field_value": "101",
        "field_destination": "personal_information",
        "field_display_name": "sdsdscs",
        "user_imports_display": "Custom5 (6. custom personal integer field)"
      }
    ],
  },
  {
    "id": "8014f51c-d2f7-4977-94f0-685a30aab050",
    "avatar_url" : 'http://lorempixel.com/640/480/people/',
    "employee_id": "",
    "first_name": "Emp_03",
    "last_name": "User",
    "nickname": null,
    "email": "emergency_03@csvnew.com",
    "date_of_birth": "1980-02-25",
    "home_phone": null,
    "cell_phone": "123-321-1236",
    "social_security_number": "XXX-XX-2312",
    "gender": "Male",
    "marital_status": "Single",
    "employment_status": "Active",
    "employment_type": "Full-time",
    "job_category": "Category-10",
    "title": null,
    "role": "company_admin",
    "department": "Marketing",
    "manager": {
      "id": null,
      "first_name": null,
      "last_name": null,
      "email": null
    },
    "location": "Omaha",
    "address1": "48 Ginger Cove",
    "address2": null,
    "city": "Omaha",
    "state": "",
    "zip_code": "68064",
    "country": "US",
    "hire_date": "1991-01-01",
    "termination_date": null,
    "rehire_date": null,
    "created_at": "2017-07-25T13:10:51.098-07:00",
    "updated_at": "2017-10-11T15:53:06.484-07:00",
    "custom_fields": [
      {
        "id": 1,
        "field_name": "Custom1",
        "field_type": "Select",
        "field_value": "a,b,c,d",
        "field_destination": "employment_compensation",
        "field_display_name": "",
        "user_imports_display": "Custom1 (1. custom employment select field)"
      },
      {
        "id": 2,
        "field_name": "Custom4",
        "field_type": "Float",
        "field_value": "108.00",
        "field_destination": "employment_compensation",
        "field_display_name": null,
        "user_imports_display": "Custom4 (2. custom employment float field)"
      },
      {
        "id": 3,
        "field_name": "Custom6",
        "field_type": "Multivalue",
        "field_value": "ABC,DEF,EFG",
        "field_destination": "employment_compensation",
        "field_display_name": "cust32dsd",
        "user_imports_display": "Custom6 (3. custom employment multivalue field)"
      },
      {
        "id": 4,
        "field_name": "Custom2",
        "field_type": "Boolean",
        "field_value": "false",
        "field_destination": "personal_information",
        "field_display_name": null,
        "user_imports_display": "Custom2 (4. custom personal boolean field)"
      },
      {
        "id": 5,
        "field_name": "Custom3",
        "field_type": "Date",
        "field_value": "01/01/2016",
        "field_destination": "personal_information",
        "field_display_name": null,
        "user_imports_display": "Custom3 (5. custom personal date field)"
      },
      {
        "id": 6,
        "field_name": "Custom5",
        "field_type": "Integer",
        "field_value": "101",
        "field_destination": "personal_information",
        "field_display_name": "sdsdscs",
        "user_imports_display": "Custom5 (6. custom personal integer field)"
      }
    ],
  },
  {
    "id": "10e047f7-dde3-427f-ac80-51e6407c86da",
    "avatar_url" : 'http://lorempixel.com/640/480/people/',
    "employee_id": "",
    "first_name": "Greg",
    "last_name": "Stojcic",
    "nickname": null,
    "email": "greg@example.com",
    "date_of_birth": null,
    "home_phone": null,
    "cell_phone": null,
    "social_security_number": "XXX-XX-",
    "gender": "Unknown",
    "marital_status": null,
    "employment_status": "Active",
    "employment_type": "Temp/Intern",
    "job_category": "Account Managment",
    "title": "Senior Technical Engineer",
    "role": "company_admin",
    "department": "Client Services",
    "manager": {
      "id": null,
      "first_name": null,
      "last_name": null,
      "email": null
    },
    "location": "San Mateo",
    "address1": null,
    "address2": null,
    "city": null,
    "state": "",
    "zip_code": null,
    "country": "US",
    "hire_date": "2015-01-20",
    "termination_date": null,
    "rehire_date": null,
    "created_at": "2017-06-05T15:44:53.528-07:00",
    "updated_at": "2017-10-18T10:19:16.039-07:00",
    "custom_fields": [
      {
        "id": 1,
        "field_name": "Custom1",
        "field_type": "Select",
        "field_value": "a,b,c,d",
        "field_destination": "employment_compensation",
        "field_display_name": "",
        "user_imports_display": "Custom1 (1. custom employment select field)"
      },
      {
        "id": 2,
        "field_name": "Custom4",
        "field_type": "Float",
        "field_value": "108.00",
        "field_destination": "employment_compensation",
        "field_display_name": null,
        "user_imports_display": "Custom4 (2. custom employment float field)"
      },
      {
        "id": 3,
        "field_name": "Custom6",
        "field_type": "Multivalue",
        "field_value": "ABC,DEF,EFG",
        "field_destination": "employment_compensation",
        "field_display_name": "cust32dsd",
        "user_imports_display": "Custom6 (3. custom employment multivalue field)"
      },
      {
        "id": 4,
        "field_name": "Custom2",
        "field_type": "Boolean",
        "field_value": "false",
        "field_destination": "personal_information",
        "field_display_name": null,
        "user_imports_display": "Custom2 (4. custom personal boolean field)"
      },
      {
        "id": 5,
        "field_name": "Custom3",
        "field_type": "Date",
        "field_value": "01/01/2016",
        "field_destination": "personal_information",
        "field_display_name": null,
        "user_imports_display": "Custom3 (5. custom personal date field)"
      },
      {
        "id": 6,
        "field_name": "Custom5",
        "field_type": "Integer",
        "field_value": "101",
        "field_destination": "personal_information",
        "field_display_name": "sdsdscs",
        "user_imports_display": "Custom5 (6. custom personal integer field)"
      }
    ],
  },
  {
    "id": "2ff01ccb-cc8b-4425-b4bf-e7c945c7345c",
    "avatar_url" : 'http://lorempixel.com/640/480/people/',
    "employee_id": "",
    "first_name": "A61",
    "last_name": "Emp",
    "nickname": null,
    "email": "testcc061+e0@gmail.com",
    "date_of_birth": "1980-10-21",
    "home_phone": null,
    "cell_phone": "327-864-3728",
    "social_security_number": "XXX-XX-8326",
    "gender": "Male",
    "marital_status": "Married",
    "employment_status": "Active",
    "employment_type": "Full-time",
    "job_category": "Engineering",
    "title": "",
    "role": "company_admin",
    "department": null,
    "manager": {
      "id": null,
      "first_name": null,
      "last_name": null,
      "email": null
    },
    "location": "Monkton",
    "address1": "Add1",
    "address2": "Add2",
    "city": "Monkton",
    "state": "",
    "zip_code": "21111",
    "country": "",
    "hire_date": "2016-10-24",
    "termination_date": null,
    "rehire_date": null,
    "custom_fields":[],
    "created_at": "2016-10-26T01:57:36.346-07:00",
    "updated_at": "2017-10-18T13:45:31.191-07:00",
  },
  {
    "id": "6c635931-1dbf-4ce5-b52d-4811d3404866",
    "avatar_url" : 'http://lorempixel.com/640/480/people/',
    "employee_id": "",
    "first_name": "A63",
    "last_name": "Emp",
    "nickname": null,
    "email": "testcc063+e0@gmail.com",
    "date_of_birth": "1980-10-06",
    "home_phone": null,
    "cell_phone": "456-757-8667",
    "social_security_number": "XXX-XX-7846",
    "gender": "Male",
    "marital_status": "Married",
    "employment_status": "Active",
    "employment_type": "Full-time",
    "job_category": "Engineering",
    "title": "Engineering",
    "role": "company_admin",
    "department": null,
    "manager": {
      "id": null,
      "first_name": null,
      "last_name": null,
      "email": null
    },
    "location": "Monkton",
    "address1": "Add1",
    "address2": "Add2",
    "city": "Monkton",
    "state": "",
    "zip_code": "21111",
    "country": "",
    "hire_date": "2016-11-01",
    "termination_date": null,
    "rehire_date": null,
    "custom_fields":[],
    "created_at": "2016-11-07T02:01:44.030-08:00",
    "updated_at": "2017-10-18T13:45:31.250-07:00",
  },
  {
    "id": "7f5dec0c-b231-49df-a9dc-6e99dd4e221d",
    "avatar_url" : 'http://lorempixel.com/640/480/people/',
    "employee_id": "",
    "first_name": "Sterling",
    "last_name": "Archer",
    "nickname": null,
    "email": null,
    "date_of_birth": "1975-08-20",
    "home_phone": null,
    "cell_phone": null,
    "social_security_number": "XXX-XX-",
    "gender": "Male",
    "marital_status": "Married",
    "employment_status": "Active",
    "employment_type": "Full-time",
    "job_category": "N/A",
    "title": null,
    "role": "company_admin",
    "department": null,
    "manager": {
      "id": null,
      "first_name": null,
      "last_name": null,
      "email": null
    },
    "location": null,
    "address1": "17305 Davenport St",
    "address2": null,
    "city": "San Diego",
    "state": "",
    "zip_code": "92109",
    "country": "US",
    "hire_date": "1981-01-15",
    "termination_date": null,
    "rehire_date": null,
    "created_at": "2017-09-18T12:11:38.178-07:00",
    "updated_at": "2017-10-11T15:53:06.786-07:00",
    "custom_fields": [
      {
        "id": 1,
        "field_name": "Custom1",
        "field_type": "Select",
        "field_value": "a,b,c,d",
        "field_destination": "employment_compensation",
        "field_display_name": "",
        "user_imports_display": "Custom1 (1. custom employment select field)"
      },
      {
        "id": 2,
        "field_name": "Custom4",
        "field_type": "Float",
        "field_value": "108.00",
        "field_destination": "employment_compensation",
        "field_display_name": null,
        "user_imports_display": "Custom4 (2. custom employment float field)"
      },
      {
        "id": 3,
        "field_name": "Custom6",
        "field_type": "Multivalue",
        "field_value": "ABC,DEF,EFG",
        "field_destination": "employment_compensation",
        "field_display_name": "cust32dsd",
        "user_imports_display": "Custom6 (3. custom employment multivalue field)"
      },
      {
        "id": 4,
        "field_name": "Custom2",
        "field_type": "Boolean",
        "field_value": "false",
        "field_destination": "personal_information",
        "field_display_name": null,
        "user_imports_display": "Custom2 (4. custom personal boolean field)"
      },
      {
        "id": 5,
        "field_name": "Custom3",
        "field_type": "Date",
        "field_value": "01/01/2016",
        "field_destination": "personal_information",
        "field_display_name": null,
        "user_imports_display": "Custom3 (5. custom personal date field)"
      },
      {
        "id": 6,
        "field_name": "Custom5",
        "field_type": "Integer",
        "field_value": "101",
        "field_destination": "personal_information",
        "field_display_name": "sdsdscs",
        "user_imports_display": "Custom5 (6. custom personal integer field)"
      }
    ],
  },
  {
    "id": "0b0a7158-e578-429a-87a4-b29cbbbf4445",
    "avatar_url" : 'http://lorempixel.com/640/480/people/',
    "employee_id": "",
    "first_name": "pwtest1",
    "last_name": "pwtest1",
    "nickname": null,
    "email": null,
    "date_of_birth": "1975-08-20",
    "home_phone": null,
    "cell_phone": null,
    "social_security_number": "XXX-XX-",
    "gender": "Male",
    "marital_status": "Married",
    "employment_status": "Active",
    "employment_type": "Full-time",
    "job_category": "N/A",
    "title": null,
    "role": "company_admin",
    "department": null,
    "manager": {
      "id": null,
      "first_name": null,
      "last_name": null,
      "email": null
    },
    "location": null,
    "address1": "17305 Davenport St",
    "address2": null,
    "city": "San Diego",
    "state": "",
    "zip_code": "92109",
    "country": "US",
    "hire_date": "1981-01-15",
    "termination_date": null,
    "rehire_date": null,
    "created_at": "2017-09-18T12:28:41.782-07:00",
    "updated_at": "2017-10-11T15:53:06.938-07:00",
    "custom_fields": [
      {
        "id": 1,
        "field_name": "Custom1",
        "field_type": "Select",
        "field_value": "a,b,c,d",
        "field_destination": "employment_compensation",
        "field_display_name": "",
        "user_imports_display": "Custom1 (1. custom employment select field)"
      },
      {
        "id": 2,
        "field_name": "Custom4",
        "field_type": "Float",
        "field_value": "108.00",
        "field_destination": "employment_compensation",
        "field_display_name": null,
        "user_imports_display": "Custom4 (2. custom employment float field)"
      },
      {
        "id": 3,
        "field_name": "Custom6",
        "field_type": "Multivalue",
        "field_value": "ABC,DEF,EFG",
        "field_destination": "employment_compensation",
        "field_display_name": "cust32dsd",
        "user_imports_display": "Custom6 (3. custom employment multivalue field)"
      },
      {
        "id": 4,
        "field_name": "Custom2",
        "field_type": "Boolean",
        "field_value": "false",
        "field_destination": "personal_information",
        "field_display_name": null,
        "user_imports_display": "Custom2 (4. custom personal boolean field)"
      },
      {
        "id": 5,
        "field_name": "Custom3",
        "field_type": "Date",
        "field_value": "01/01/2016",
        "field_destination": "personal_information",
        "field_display_name": null,
        "user_imports_display": "Custom3 (5. custom personal date field)"
      },
      {
        "id": 6,
        "field_name": "Custom5",
        "field_type": "Integer",
        "field_value": "101",
        "field_destination": "personal_information",
        "field_display_name": "sdsdscs",
        "user_imports_display": "Custom5 (6. custom personal integer field)"
      }
    ],
  },
  {
    "id": "75ce3a46-ebdb-44a2-b0e4-d782498e4cba",
    "avatar_url" : 'http://lorempixel.com/640/480/people/',
    "employee_id": "",
    "first_name": "Emp_02",
    "last_name": "User",
    "nickname": null,
    "email": "speedtest_local_05_08@csvnew.com",
    "date_of_birth": "1975-08-20",
    "home_phone": null,
    "cell_phone": "123-321-1234",
    "social_security_number": "XXX-XX-7892",
    "gender": "Male",
    "marital_status": "Married",
    "employment_status": "Active",
    "employment_type": "Full-time",
    "job_category": "Management",
    "title": null,
    "role": "company_admin",
    "department": "Sales",
    "manager": {
      "id": null,
      "first_name": null,
      "last_name": null,
      "email": null
    },
    "location": "Omaha",
    "address1": "17305 Davenport St",
    "address2": null,
    "city": "Omaha",
    "state": "",
    "zip_code": "68118",
    "country": "US",
    "hire_date": "1981-01-01",
    "termination_date": null,
    "rehire_date": null,
    "created_at": "2017-08-04T16:41:37.588-07:00",
    "updated_at": "2017-08-23T09:21:29.149-07:00",
    "custom_fields": [
      {
        "id": 1,
        "field_name": "Custom1",
        "field_type": "Select",
        "field_value": "a,b,c,d",
        "field_destination": "employment_compensation",
        "field_display_name": "",
        "user_imports_display": "Custom1 (1. custom employment select field)"
      },
      {
        "id": 2,
        "field_name": "Custom4",
        "field_type": "Float",
        "field_value": "108.00",
        "field_destination": "employment_compensation",
        "field_display_name": null,
        "user_imports_display": "Custom4 (2. custom employment float field)"
      },
      {
        "id": 3,
        "field_name": "Custom6",
        "field_type": "Multivalue",
        "field_value": "ABC,DEF,EFG",
        "field_destination": "employment_compensation",
        "field_display_name": "cust32dsd",
        "user_imports_display": "Custom6 (3. custom employment multivalue field)"
      },
      {
        "id": 4,
        "field_name": "Custom2",
        "field_type": "Boolean",
        "field_value": "false",
        "field_destination": "personal_information",
        "field_display_name": null,
        "user_imports_display": "Custom2 (4. custom personal boolean field)"
      },
      {
        "id": 5,
        "field_name": "Custom3",
        "field_type": "Date",
        "field_value": "01/01/2016",
        "field_destination": "personal_information",
        "field_display_name": null,
        "user_imports_display": "Custom3 (5. custom personal date field)"
      },
      {
        "id": 6,
        "field_name": "Custom5",
        "field_type": "Integer",
        "field_value": "101",
        "field_destination": "personal_information",
        "field_display_name": "sdsdscs",
        "user_imports_display": "Custom5 (6. custom personal integer field)"
      }
    ],
  },
  {
    "id": "bdb94ddf-f7b1-4f77-b949-94d365a0b837",
    "avatar_url" : 'http://lorempixel.com/640/480/people/',
    "employee_id": "",
    "first_name": "Emp_02",
    "last_name": "User",
    "nickname": null,
    "email": "speedtest_local_05_04@csvnew.com",
    "date_of_birth": "1975-08-20",
    "home_phone": null,
    "cell_phone": "123-321-1234",
    "social_security_number": "XXX-XX-7892",
    "gender": "Male",
    "marital_status": "Married",
    "employment_status": "Active",
    "employment_type": "Full-time",
    "job_category": "Management",
    "title": null,
    "role": "company_admin",
    "department": "Sales",
    "manager": {
      "id": null,
      "first_name": null,
      "last_name": null,
      "email": null
    },
    "location": "Omaha",
    "address1": "17305 Davenport St",
    "address2": null,
    "city": "Omaha",
    "state": "",
    "zip_code": "68118",
    "country": "US",
    "hire_date": "1981-01-01",
    "termination_date": null,
    "rehire_date": null,
    "created_at": "2017-08-04T16:19:53.716-07:00",
    "updated_at": "2017-08-23T09:21:29.789-07:00",
    "custom_fields": [
      {
        "id": 1,
        "field_name": "Custom1",
        "field_type": "Select",
        "field_value": "a,b,c,d",
        "field_destination": "employment_compensation",
        "field_display_name": "",
        "user_imports_display": "Custom1 (1. custom employment select field)"
      },
      {
        "id": 2,
        "field_name": "Custom4",
        "field_type": "Float",
        "field_value": "108.00",
        "field_destination": "employment_compensation",
        "field_display_name": null,
        "user_imports_display": "Custom4 (2. custom employment float field)"
      },
      {
        "id": 3,
        "field_name": "Custom6",
        "field_type": "Multivalue",
        "field_value": "ABC,DEF,EFG",
        "field_destination": "employment_compensation",
        "field_display_name": "cust32dsd",
        "user_imports_display": "Custom6 (3. custom employment multivalue field)"
      },
      {
        "id": 4,
        "field_name": "Custom2",
        "field_type": "Boolean",
        "field_value": "false",
        "field_destination": "personal_information",
        "field_display_name": null,
        "user_imports_display": "Custom2 (4. custom personal boolean field)"
      },
      {
        "id": 5,
        "field_name": "Custom3",
        "field_type": "Date",
        "field_value": "01/01/2016",
        "field_destination": "personal_information",
        "field_display_name": null,
        "user_imports_display": "Custom3 (5. custom personal date field)"
      },
      {
        "id": 6,
        "field_name": "Custom5",
        "field_type": "Integer",
        "field_value": "101",
        "field_destination": "personal_information",
        "field_display_name": "sdsdscs",
        "user_imports_display": "Custom5 (6. custom personal integer field)"
      }
    ],
  },
  {
    "id": "b82f7214-48d6-4467-b643-8078813856d0",
    "avatar_url" : 'http://lorempixel.com/640/480/people/',
    "employee_id": "",
    "first_name": "A163",
    "last_name": "Emp",
    "nickname": null,
    "email": "testcc163+e0@gmail.com",
    "date_of_birth": "1975-08-20",
    "home_phone": null,
    "cell_phone": "123-321-1234",
    "social_security_number": "XXX-XX-7892",
    "gender": "Male",
    "marital_status": "Married",
    "employment_status": "Active",
    "employment_type": "Full-time",
    "job_category": "Sales",
    "title": null,
    "role": "company_admin",
    "department": "Sales",
    "manager": {
      "id": null,
      "first_name": null,
      "last_name": null,
      "email": null
    },
    "location": "Monkton",
    "address1": "17305 Davenport St",
    "address2": null,
    "city": "Monkton",
    "state": "",
    "zip_code": "68118",
    "country": "US",
    "hire_date": "2017-08-01",
    "termination_date": null,
    "rehire_date": null,
    "created_at": "2017-08-28T12:20:09.546-07:00",
    "updated_at": "2017-10-11T15:53:07.017-07:00",
    "custom_fields": [
      {
        "id": 1,
        "field_name": "Custom1",
        "field_type": "Select",
        "field_value": "a,b,c,d",
        "field_destination": "employment_compensation",
        "field_display_name": "",
        "user_imports_display": "Custom1 (1. custom employment select field)"
      },
      {
        "id": 2,
        "field_name": "Custom4",
        "field_type": "Float",
        "field_value": "108.00",
        "field_destination": "employment_compensation",
        "field_display_name": null,
        "user_imports_display": "Custom4 (2. custom employment float field)"
      },
      {
        "id": 3,
        "field_name": "Custom6",
        "field_type": "Multivalue",
        "field_value": "ABC,DEF,EFG",
        "field_destination": "employment_compensation",
        "field_display_name": "cust32dsd",
        "user_imports_display": "Custom6 (3. custom employment multivalue field)"
      },
      {
        "id": 4,
        "field_name": "Custom2",
        "field_type": "Boolean",
        "field_value": "false",
        "field_destination": "personal_information",
        "field_display_name": null,
        "user_imports_display": "Custom2 (4. custom personal boolean field)"
      },
      {
        "id": 5,
        "field_name": "Custom3",
        "field_type": "Date",
        "field_value": "01/01/2016",
        "field_destination": "personal_information",
        "field_display_name": null,
        "user_imports_display": "Custom3 (5. custom personal date field)"
      },
      {
        "id": 6,
        "field_name": "Custom5",
        "field_type": "Integer",
        "field_value": "101",
        "field_destination": "personal_information",
        "field_display_name": "sdsdscs",
        "user_imports_display": "Custom5 (6. custom personal integer field)"
      }
    ],
  },
  {
    "id": "0a201e4a-e612-4792-802a-a294090bb841",
    "avatar_url" : 'http://lorempixel.com/640/480/people/',
    "employee_id": "",
    "first_name": "A164",
    "last_name": "Emp",
    "nickname": null,
    "email": "testcc164+e0@gmail.com",
    "date_of_birth": "1975-08-20",
    "home_phone": null,
    "cell_phone": "123-321-1234",
    "social_security_number": "XXX-XX-7892",
    "gender": "Male",
    "marital_status": "Married",
    "employment_status": "Active",
    "employment_type": "Full-time",
    "job_category": "Sales",
    "title": null,
    "role": "company_admin",
    "department": "Sales",
    "manager": {
      "id": null,
      "first_name": null,
      "last_name": null,
      "email": null
    },
    "location": "Monkton",
    "address1": "17305 Davenport St",
    "address2": null,
    "city": "Monkton",
    "state": "",
    "zip_code": "68118",
    "country": "US",
    "hire_date": "2017-08-01",
    "termination_date": null,
    "rehire_date": null,
    "created_at": "2017-08-28T12:27:36.022-07:00",
    "updated_at": "2017-10-11T15:53:07.377-07:00",
    "custom_fields": [
      {
        "id": 1,
        "field_name": "Custom1",
        "field_type": "Select",
        "field_value": "a,b,c,d",
        "field_destination": "employment_compensation",
        "field_display_name": "",
        "user_imports_display": "Custom1 (1. custom employment select field)"
      },
      {
        "id": 2,
        "field_name": "Custom4",
        "field_type": "Float",
        "field_value": "108.00",
        "field_destination": "employment_compensation",
        "field_display_name": null,
        "user_imports_display": "Custom4 (2. custom employment float field)"
      },
      {
        "id": 3,
        "field_name": "Custom6",
        "field_type": "Multivalue",
        "field_value": "ABC,DEF,EFG",
        "field_destination": "employment_compensation",
        "field_display_name": "cust32dsd",
        "user_imports_display": "Custom6 (3. custom employment multivalue field)"
      },
      {
        "id": 4,
        "field_name": "Custom2",
        "field_type": "Boolean",
        "field_value": "false",
        "field_destination": "personal_information",
        "field_display_name": null,
        "user_imports_display": "Custom2 (4. custom personal boolean field)"
      },
      {
        "id": 5,
        "field_name": "Custom3",
        "field_type": "Date",
        "field_value": "01/01/2016",
        "field_destination": "personal_information",
        "field_display_name": null,
        "user_imports_display": "Custom3 (5. custom personal date field)"
      },
      {
        "id": 6,
        "field_name": "Custom5",
        "field_type": "Integer",
        "field_value": "101",
        "field_destination": "personal_information",
        "field_display_name": "sdsdscs",
        "user_imports_display": "Custom5 (6. custom personal integer field)"
      }
    ],
  },
  {
    "id": "593c6f1f-dc91-4939-bc58-347f0dde2e76",
    "avatar_url" : 'http://lorempixel.com/640/480/people/',
    "employee_id": "1009",
    "first_name": "Robert",
    "last_name": "asdfasdf",
    "nickname": "Bobby",
    "email": "sample_03@csvnew.com",
    "date_of_birth": "1975-08-20",
    "home_phone": null,
    "cell_phone": "123-321-1234",
    "social_security_number": "XXX-XX-7892",
    "gender": "Male",
    "marital_status": "Married",
    "employment_status": "Active",
    "employment_type": "Full-time",
    "job_category": "Sales",
    "title": "Account Executive",
    "role": "company_admin",
    "department": "New Business",
    "manager": {
      "id": null,
      "first_name": null,
      "last_name": null,
      "email": null
    },
    "location": "California",
    "address1": "17305 Davenport St",
    "address2": null,
    "city": "San Diego",
    "state": "",
    "zip_code": "92109",
    "country": "US",
    "hire_date": "1981-01-15",
    "termination_date": null,
    "rehire_date": null,
    "created_at": "2017-06-02T15:40:54.847-07:00",
    "updated_at": "2017-09-21T14:36:17.819-07:00",
    "custom_fields": [
      {
        "id": 1,
        "field_name": "Custom1",
        "field_type": "Select",
        "field_value": "a,b,c,d",
        "field_destination": "employment_compensation",
        "field_display_name": "",
        "user_imports_display": "Custom1 (1. custom employment select field)"
      },
      {
        "id": 2,
        "field_name": "Custom4",
        "field_type": "Float",
        "field_value": "108.00",
        "field_destination": "employment_compensation",
        "field_display_name": null,
        "user_imports_display": "Custom4 (2. custom employment float field)"
      },
      {
        "id": 3,
        "field_name": "Custom6",
        "field_type": "Multivalue",
        "field_value": "ABC,DEF,EFG",
        "field_destination": "employment_compensation",
        "field_display_name": "cust32dsd",
        "user_imports_display": "Custom6 (3. custom employment multivalue field)"
      },
      {
        "id": 4,
        "field_name": "Custom2",
        "field_type": "Boolean",
        "field_value": "false",
        "field_destination": "personal_information",
        "field_display_name": null,
        "user_imports_display": "Custom2 (4. custom personal boolean field)"
      },
      {
        "id": 5,
        "field_name": "Custom3",
        "field_type": "Date",
        "field_value": "01/01/2016",
        "field_destination": "personal_information",
        "field_display_name": null,
        "user_imports_display": "Custom3 (5. custom personal date field)"
      },
      {
        "id": 6,
        "field_name": "Custom5",
        "field_type": "Integer",
        "field_value": "101",
        "field_destination": "personal_information",
        "field_display_name": "sdsdscs",
        "user_imports_display": "Custom5 (6. custom personal integer field)"
      }
    ],
  },
  {
    "id": "ea54f8d6-c1d6-4ba9-834c-52c76cce4d16",
    "avatar_url" : 'http://lorempixel.com/640/480/people/',
    "employee_id": "",
    "first_name": "Hetasdfe",
    "last_name": "Basdfrg",
    "nickname": null,
    "email": "growthcasdfasdfaode@gmail.com",
    "date_of_birth": null,
    "home_phone": null,
    "cell_phone": "(402) 980-8144",
    "social_security_number": "XXX-XX-",
    "gender": "Unknown",
    "marital_status": null,
    "employment_status": "Active",
    "employment_type": "Full-time",
    "job_category": "Accounts",
    "title": null,
    "role": "company_admin",
    "department": null,
    "manager": {
      "id": null,
      "first_name": null,
      "last_name": null,
      "email": null
    },
    "location": "Brooklyn",
    "address1": null,
    "address2": null,
    "city": null,
    "state": "",
    "zip_code": null,
    "country": "United States",
    "hire_date": "2017-08-15",
    "termination_date": null,
    "rehire_date": null,
    "custom_fields":[],
    "created_at": "2017-08-15T10:48:26.321-07:00",
    "updated_at": "2017-08-17T15:15:13.020-07:00",
  },
  {
    "id": "a7c34b9c-7147-4674-8771-9e8fa56bc2ba",
    "avatar_url" : 'http://lorempixel.com/640/480/people/',
    "employee_id": "",
    "first_name": "pwtest3",
    "last_name": "pwtest3",
    "nickname": null,
    "email": null,
    "date_of_birth": "1975-08-20",
    "home_phone": null,
    "cell_phone": null,
    "social_security_number": "XXX-XX-",
    "gender": "Male",
    "marital_status": "Married",
    "employment_status": "Active",
    "employment_type": "Full-time",
    "job_category": "N/A",
    "title": null,
    "role": "company_admin",
    "department": null,
    "manager": {
      "id": null,
      "first_name": null,
      "last_name": null,
      "email": null
    },
    "location": null,
    "address1": "17305 Davenport St",
    "address2": null,
    "city": "San Diego",
    "state": "",
    "zip_code": "92109",
    "country": "US",
    "hire_date": "1981-01-15",
    "termination_date": null,
    "rehire_date": null,
    "created_at": "2017-09-18T12:32:22.059-07:00",
    "updated_at": "2017-10-11T15:53:07.449-07:00",
    "custom_fields": [
      {
        "id": 1,
        "field_name": "Custom1",
        "field_type": "Select",
        "field_value": "a,b,c,d",
        "field_destination": "employment_compensation",
        "field_display_name": "",
        "user_imports_display": "Custom1 (1. custom employment select field)"
      },
      {
        "id": 2,
        "field_name": "Custom4",
        "field_type": "Float",
        "field_value": "108.00",
        "field_destination": "employment_compensation",
        "field_display_name": null,
        "user_imports_display": "Custom4 (2. custom employment float field)"
      },
      {
        "id": 3,
        "field_name": "Custom6",
        "field_type": "Multivalue",
        "field_value": "ABC,DEF,EFG",
        "field_destination": "employment_compensation",
        "field_display_name": "cust32dsd",
        "user_imports_display": "Custom6 (3. custom employment multivalue field)"
      },
      {
        "id": 4,
        "field_name": "Custom2",
        "field_type": "Boolean",
        "field_value": "false",
        "field_destination": "personal_information",
        "field_display_name": null,
        "user_imports_display": "Custom2 (4. custom personal boolean field)"
      },
      {
        "id": 5,
        "field_name": "Custom3",
        "field_type": "Date",
        "field_value": "01/01/2016",
        "field_destination": "personal_information",
        "field_display_name": null,
        "user_imports_display": "Custom3 (5. custom personal date field)"
      },
      {
        "id": 6,
        "field_name": "Custom5",
        "field_type": "Integer",
        "field_value": "101",
        "field_destination": "personal_information",
        "field_display_name": "sdsdscs",
        "user_imports_display": "Custom5 (6. custom personal integer field)"
      }
    ],
  },
  {
    "id": "f0136a87-57b8-4a56-83cf-fe776d5f69bc",
    "avatar_url" : 'http://lorempixel.com/640/480/people/',
    "employee_id": "",
    "first_name": "Aonenottwo",
    "last_name": "Emp",
    "nickname": null,
    "email": "testcc10asdf2+e0@gmail.com",
    "date_of_birth": null,
    "home_phone": null,
    "cell_phone": null,
    "social_security_number": "XXX-XX-",
    "gender": "Unknown",
    "marital_status": null,
    "employment_status": "Active",
    "employment_type": "Full-time",
    "job_category": "N/A",
    "title": "Marketing",
    "role": "company_admin",
    "department": null,
    "manager": {
      "id": null,
      "first_name": null,
      "last_name": null,
      "email": null
    },
    "location": null,
    "address1": null,
    "address2": null,
    "city": null,
    "state": "",
    "zip_code": null,
    "country": "United States",
    "hire_date": "2017-03-27",
    "termination_date": null,
    "rehire_date": null,
    "custom_fields":[],
    "created_at": "2017-08-15T10:55:07.938-07:00",
    "updated_at": "2017-10-11T15:53:07.527-07:00",
  },
  {
    "id": "f207091f-6f49-4c3f-86d5-106462cc65bd",
    "avatar_url" : 'http://lorempixel.com/640/480/people/',
    "employee_id": "",
    "first_name": "A163",
    "last_name": "Emp",
    "nickname": null,
    "email": "testcc163_01+e0@gmail.com",
    "date_of_birth": "1975-08-20",
    "home_phone": null,
    "cell_phone": "123-321-1234",
    "social_security_number": "XXX-XX-7892",
    "gender": "Male",
    "marital_status": "Married",
    "employment_status": "Active",
    "employment_type": "Full-time",
    "job_category": "Sales",
    "title": null,
    "role": "company_admin",
    "department": "Sales",
    "manager": {
      "id": null,
      "first_name": null,
      "last_name": null,
      "email": null
    },
    "location": "Monkton",
    "address1": "17305 Davenport St",
    "address2": null,
    "city": "Monkton",
    "state": "",
    "zip_code": "68118",
    "country": "US",
    "hire_date": "2017-08-01",
    "termination_date": null,
    "rehire_date": null,
    "created_at": "2017-08-28T12:39:40.346-07:00",
    "updated_at": "2017-10-11T15:53:07.594-07:00",
    "custom_fields": [
      {
        "id": 1,
        "field_name": "Custom1",
        "field_type": "Select",
        "field_value": "a,b,c,d",
        "field_destination": "employment_compensation",
        "field_display_name": "",
        "user_imports_display": "Custom1 (1. custom employment select field)"
      },
      {
        "id": 2,
        "field_name": "Custom4",
        "field_type": "Float",
        "field_value": "108.00",
        "field_destination": "employment_compensation",
        "field_display_name": null,
        "user_imports_display": "Custom4 (2. custom employment float field)"
      },
      {
        "id": 3,
        "field_name": "Custom6",
        "field_type": "Multivalue",
        "field_value": "ABC,DEF,EFG",
        "field_destination": "employment_compensation",
        "field_display_name": "cust32dsd",
        "user_imports_display": "Custom6 (3. custom employment multivalue field)"
      },
      {
        "id": 4,
        "field_name": "Custom2",
        "field_type": "Boolean",
        "field_value": "false",
        "field_destination": "personal_information",
        "field_display_name": null,
        "user_imports_display": "Custom2 (4. custom personal boolean field)"
      },
      {
        "id": 5,
        "field_name": "Custom3",
        "field_type": "Date",
        "field_value": "01/01/2016",
        "field_destination": "personal_information",
        "field_display_name": null,
        "user_imports_display": "Custom3 (5. custom personal date field)"
      },
      {
        "id": 6,
        "field_name": "Custom5",
        "field_type": "Integer",
        "field_value": "101",
        "field_destination": "personal_information",
        "field_display_name": "sdsdscs",
        "user_imports_display": "Custom5 (6. custom personal integer field)"
      }
    ],
  },
  {
    "id": "9e41cfa2-9929-4600-83c6-4cac953dc908",
    "avatar_url" : 'http://lorempixel.com/640/480/people/',
    "employee_id": "",
    "first_name": "pwtest4",
    "last_name": "pwtest4",
    "nickname": null,
    "email": null,
    "date_of_birth": "1975-08-20",
    "home_phone": null,
    "cell_phone": null,
    "social_security_number": "XXX-XX-6789",
    "gender": "Male",
    "marital_status": "Married",
    "employment_status": "Active",
    "employment_type": "Full-time",
    "job_category": "N/A",
    "title": null,
    "role": "company_admin",
    "department": null,
    "manager": {
      "id": null,
      "first_name": null,
      "last_name": null,
      "email": null
    },
    "location": null,
    "address1": "17305 Davenport St",
    "address2": null,
    "city": "San Diego",
    "state": "",
    "zip_code": "92109",
    "country": "US",
    "hire_date": "1981-01-15",
    "termination_date": null,
    "rehire_date": null,
    "created_at": "2017-09-18T12:41:24.280-07:00",
    "updated_at": "2017-10-11T15:53:07.666-07:00",
    "custom_fields": [
      {
        "id": 1,
        "field_name": "Custom1",
        "field_type": "Select",
        "field_value": "a,b,c,d",
        "field_destination": "employment_compensation",
        "field_display_name": "",
        "user_imports_display": "Custom1 (1. custom employment select field)"
      },
      {
        "id": 2,
        "field_name": "Custom4",
        "field_type": "Float",
        "field_value": "108.00",
        "field_destination": "employment_compensation",
        "field_display_name": null,
        "user_imports_display": "Custom4 (2. custom employment float field)"
      },
      {
        "id": 3,
        "field_name": "Custom6",
        "field_type": "Multivalue",
        "field_value": "ABC,DEF,EFG",
        "field_destination": "employment_compensation",
        "field_display_name": "cust32dsd",
        "user_imports_display": "Custom6 (3. custom employment multivalue field)"
      },
      {
        "id": 4,
        "field_name": "Custom2",
        "field_type": "Boolean",
        "field_value": "false",
        "field_destination": "personal_information",
        "field_display_name": null,
        "user_imports_display": "Custom2 (4. custom personal boolean field)"
      },
      {
        "id": 5,
        "field_name": "Custom3",
        "field_type": "Date",
        "field_value": "01/01/2016",
        "field_destination": "personal_information",
        "field_display_name": null,
        "user_imports_display": "Custom3 (5. custom personal date field)"
      },
      {
        "id": 6,
        "field_name": "Custom5",
        "field_type": "Integer",
        "field_value": "101",
        "field_destination": "personal_information",
        "field_display_name": "sdsdscs",
        "user_imports_display": "Custom5 (6. custom personal integer field)"
      }
    ],
  },
]
